name: Feature request
description: Propose and discuss future improvements to Lucia
title: "[Feature Request]: "
labels: ["feature request"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this feature request!
    - type: dropdown
      id: package
      attributes:
          label: Package
          options:
              - lucia
              - ​@lucia-auth/adapter-test
              - ​@lucia-auth/adapter-mongodb
              - ​@lucia-auth/adapter-mysql
              - ​@lucia-auth/adapter-postgresql
              - ​@lucia-auth/adapter-prisma
              - ​@lucia-auth/adapter-sqlite
              - ​@lucia-auth/session-drizzle
      validations:
          required: true
    - type: textarea
      id: description
      attributes:
          label: Description
      validations:
          required: true
