// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/email-verification/:token': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/email-verification/[token].get').default>>>>
    }
    '/api/email-verification': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/email-verification/index.post').default>>>>
    }
    '/api/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login.post').default>>>>
    }
    '/api/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/logout.post').default>>>>
    }
    '/api/password-reset/:token': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/password-reset/[token].post').default>>>>
    }
    '/api/password-reset': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/password-reset/index.post').default>>>>
    }
    '/api/signup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/signup.post').default>>>>
    }
    '/api/user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/user.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../../node_modules/.pnpm/nuxt@3.6.5_fl4khuxltvm6fadgpmkxkyqtiu/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}