name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Copy code files
        run: |
          mkdir ./lucia-auth.com/code
          cp ./code/LICENSE ./lucia-auth.com/code/LICENSE.txt
          cp ./code/auth_session.ts ./lucia-auth.com/code/auth_session.ts.txt

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./lucia-auth.com"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
