name: "Publish v2 docs"
on:
  push:
    branches:
      - v2

env:
  CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_PAGES_API_TOKEN}}

jobs:
  publish-docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
      - name: setup actions
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.1
          registry-url: https://registry.npmjs.org
      - name: Install PNPM
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Build
        working-directory: documentation
        run: pnpm build
      - name: Install wrangler
        run: npm i -g wrangler
      - name: deploy
        working-directory: documentation
        run: wrangler pages deploy dist --project-name lucia-v2 --branch v2
